name: practice_nine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-134.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  http: ^1.1.0
  lottie: ^2.7.0
  retrofit: ^4.0.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  logger: any
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.1.11
  shared_preferences: ^2.2.2
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
   - assets\animations\animation.json
